kind: Service
apiVersion: v1
metadata:
  name: openldap-phpldapadmin
  namespace: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "240"
spec:
  # clusterIP: 172.21.162.213
  clusterIP: 172.21.158.45
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  internalTrafficPolicy: Cluster
  # clusterIPs:
  #   - 172.21.162.213
  clusterIPs:
    - 172.21.158.45
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: phpldapadmin
    release: openldap